apiVersion:v1 
kind: Service 
metadata: 
  annotations: 
    kompose.cmd: C:\Users\Fenerbahce\Documents\bin\kompose.exe convert 
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: Null 
  labels: 
    io.kompose.service: db 
  name: db 
spec: 
  ports: 
  - port: 27017
    targetPort: 27017
  selector: 
    io.kompose.service: db
status: 
  loadBalancer: {}

  
  
